// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(sudachi_swiftFFI)
import sudachi_swiftFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_sudachi_swift_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_sudachi_swift_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureSudachiSwiftInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
// Initial value and increment amount for handles. 
// These ensure that SWIFT handles always have the lowest bit set
fileprivate let UNIFFI_HANDLEMAP_INITIAL: UInt64 = 1
fileprivate let UNIFFI_HANDLEMAP_DELTA: UInt64 = 2

fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = UNIFFI_HANDLEMAP_INITIAL

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            return doInsert(obj)
        }
    }

    // Low-level insert function, this assumes `lock` is held.
    private func doInsert(_ obj: T) -> UInt64 {
        let handle = currentHandle
        currentHandle += UNIFFI_HANDLEMAP_DELTA
        map[handle] = obj
        return handle
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

     func clone(handle: UInt64) throws -> UInt64 {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return doInsert(obj)
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt16: FfiConverterPrimitive {
    typealias FfiType = UInt16
    typealias SwiftType = UInt16

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt16 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterInt32: FfiConverterPrimitive {
    typealias FfiType = Int32
    typealias SwiftType = Int32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Int32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Int32, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}




/**
 * A loaded Sudachi dictionary.
 *
 * Loading `mmap`s the `.dic` file, so construction is fast (~10 ms) and
 * memory is shared between tokenizers. Create it once and pass it to as many
 * `SudachiTokenizer`s as you need — the recommended pattern for parallelism
 * is one dictionary, one tokenizer per worker.
 */
public protocol SudachiDictionaryProtocol: AnyObject, Sendable {
    
}
/**
 * A loaded Sudachi dictionary.
 *
 * Loading `mmap`s the `.dic` file, so construction is fast (~10 ms) and
 * memory is shared between tokenizers. Create it once and pass it to as many
 * `SudachiTokenizer`s as you need — the recommended pattern for parallelism
 * is one dictionary, one tokenizer per worker.
 */
open class SudachiDictionary: SudachiDictionaryProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_sudachi_swift_fn_clone_sudachidictionary(self.handle, $0) }
    }
    /**
     * Load a system dictionary (`system_*.dic`), optional user dictionaries,
     * and the resource directory containing `char.def` / `unk.def`.
     *
     * All paths are plain filesystem paths. Throws `DictionaryNotFound` /
     * `ConfigInvalid` naming the offending path if anything is missing.
     */
public convenience init(systemDictPath: String, userDictPaths: [String], resourceDir: String)throws  {
    let handle =
        try rustCallWithError(FfiConverterTypeSudachiError_lift) {
    uniffi_sudachi_swift_fn_constructor_sudachidictionary_new(
        FfiConverterString.lower(systemDictPath),
        FfiConverterSequenceString.lower(userDictPaths),
        FfiConverterString.lower(resourceDir),$0
    )
}
    self.init(unsafeFromHandle: handle)
}

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_sudachi_swift_fn_free_sudachidictionary(handle, $0) }
    }

    

    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSudachiDictionary: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = SudachiDictionary

    public static func lift(_ handle: UInt64) throws -> SudachiDictionary {
        return SudachiDictionary(unsafeFromHandle: handle)
    }

    public static func lower(_ value: SudachiDictionary) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SudachiDictionary {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: SudachiDictionary, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSudachiDictionary_lift(_ handle: UInt64) throws -> SudachiDictionary {
    return try FfiConverterTypeSudachiDictionary.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSudachiDictionary_lower(_ value: SudachiDictionary) -> UInt64 {
    return FfiConverterTypeSudachiDictionary.lower(value)
}






/**
 * A tokenizer bound to a dictionary and a default `SplitMode`.
 *
 * Thread-safe: calls are serialized by an internal lock, so a single
 * instance can be shared across threads/actors. For CPU parallelism create
 * several tokenizers over the same `SudachiDictionary`.
 */
public protocol SudachiTokenizerProtocol: AnyObject, Sendable {
    
    /**
     * Tokenize `text` into full `Morpheme`s using the default split mode.
     */
    func tokenize(text: String) throws  -> [Morpheme]
    
    /**
     * Lean variant of `tokenize` returning only the fields the Swift
     * merge/display pipeline actually consumes, with `part_of_speech`
     * pre-joined into a single comma string plus an integer `pos_id`.
     * Cuts per-morpheme allocations and FFI marshalling roughly in half
     * versus the full `Morpheme`. Prefer this for hot paths (reader,
     * catalog).
     */
    func tokenizeLite(text: String) throws  -> [MorphemeLite]
    
    /**
     * Same as `tokenize_lite` but with an explicit split mode.
     */
    func tokenizeLiteWithMode(text: String, mode: SplitMode) throws  -> [MorphemeLite]
    
    /**
     * Batch tokenization: tokenize many strings in one FFI crossing,
     * reusing a single locked tokenizer. Avoids per-sentence FFI overhead
     * when processing a whole document/catalog. Uses the tokenizer's
     * default mode. (Batch is lite-only by design — needing full
     * `Morpheme`s in bulk is rare; loop `tokenize` for that.)
     */
    func tokenizeMany(texts: [String]) throws  -> [[MorphemeLite]]
    
    /**
     * Same as `tokenize_many` but with an explicit split mode.
     */
    func tokenizeManyWithMode(texts: [String], mode: SplitMode) throws  -> [[MorphemeLite]]
    
    /**
     * Re-tokenize a substring (typically a single morpheme's surface) with
     * a different split mode. Useful for showing Mode A breakdown of a
     * Mode C compound on tap, without rerunning the full pipeline.
     */
    func tokenizeWithMode(text: String, mode: SplitMode) throws  -> [Morpheme]
    
}
/**
 * A tokenizer bound to a dictionary and a default `SplitMode`.
 *
 * Thread-safe: calls are serialized by an internal lock, so a single
 * instance can be shared across threads/actors. For CPU parallelism create
 * several tokenizers over the same `SudachiDictionary`.
 */
open class SudachiTokenizer: SudachiTokenizerProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_sudachi_swift_fn_clone_sudachitokenizer(self.handle, $0) }
    }
    /**
     * Create a tokenizer over `dictionary` with a default split `mode`.
     */
public convenience init(dictionary: SudachiDictionary, mode: SplitMode)throws  {
    let handle =
        try rustCallWithError(FfiConverterTypeSudachiError_lift) {
    uniffi_sudachi_swift_fn_constructor_sudachitokenizer_new(
        FfiConverterTypeSudachiDictionary_lower(dictionary),
        FfiConverterTypeSplitMode_lower(mode),$0
    )
}
    self.init(unsafeFromHandle: handle)
}

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_sudachi_swift_fn_free_sudachitokenizer(handle, $0) }
    }

    

    
    /**
     * Tokenize `text` into full `Morpheme`s using the default split mode.
     */
open func tokenize(text: String)throws  -> [Morpheme]  {
    return try  FfiConverterSequenceTypeMorpheme.lift(try rustCallWithError(FfiConverterTypeSudachiError_lift) {
    uniffi_sudachi_swift_fn_method_sudachitokenizer_tokenize(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(text),$0
    )
})
}
    
    /**
     * Lean variant of `tokenize` returning only the fields the Swift
     * merge/display pipeline actually consumes, with `part_of_speech`
     * pre-joined into a single comma string plus an integer `pos_id`.
     * Cuts per-morpheme allocations and FFI marshalling roughly in half
     * versus the full `Morpheme`. Prefer this for hot paths (reader,
     * catalog).
     */
open func tokenizeLite(text: String)throws  -> [MorphemeLite]  {
    return try  FfiConverterSequenceTypeMorphemeLite.lift(try rustCallWithError(FfiConverterTypeSudachiError_lift) {
    uniffi_sudachi_swift_fn_method_sudachitokenizer_tokenize_lite(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(text),$0
    )
})
}
    
    /**
     * Same as `tokenize_lite` but with an explicit split mode.
     */
open func tokenizeLiteWithMode(text: String, mode: SplitMode)throws  -> [MorphemeLite]  {
    return try  FfiConverterSequenceTypeMorphemeLite.lift(try rustCallWithError(FfiConverterTypeSudachiError_lift) {
    uniffi_sudachi_swift_fn_method_sudachitokenizer_tokenize_lite_with_mode(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(text),
        FfiConverterTypeSplitMode_lower(mode),$0
    )
})
}
    
    /**
     * Batch tokenization: tokenize many strings in one FFI crossing,
     * reusing a single locked tokenizer. Avoids per-sentence FFI overhead
     * when processing a whole document/catalog. Uses the tokenizer's
     * default mode. (Batch is lite-only by design — needing full
     * `Morpheme`s in bulk is rare; loop `tokenize` for that.)
     */
open func tokenizeMany(texts: [String])throws  -> [[MorphemeLite]]  {
    return try  FfiConverterSequenceSequenceTypeMorphemeLite.lift(try rustCallWithError(FfiConverterTypeSudachiError_lift) {
    uniffi_sudachi_swift_fn_method_sudachitokenizer_tokenize_many(
            self.uniffiCloneHandle(),
        FfiConverterSequenceString.lower(texts),$0
    )
})
}
    
    /**
     * Same as `tokenize_many` but with an explicit split mode.
     */
open func tokenizeManyWithMode(texts: [String], mode: SplitMode)throws  -> [[MorphemeLite]]  {
    return try  FfiConverterSequenceSequenceTypeMorphemeLite.lift(try rustCallWithError(FfiConverterTypeSudachiError_lift) {
    uniffi_sudachi_swift_fn_method_sudachitokenizer_tokenize_many_with_mode(
            self.uniffiCloneHandle(),
        FfiConverterSequenceString.lower(texts),
        FfiConverterTypeSplitMode_lower(mode),$0
    )
})
}
    
    /**
     * Re-tokenize a substring (typically a single morpheme's surface) with
     * a different split mode. Useful for showing Mode A breakdown of a
     * Mode C compound on tap, without rerunning the full pipeline.
     */
open func tokenizeWithMode(text: String, mode: SplitMode)throws  -> [Morpheme]  {
    return try  FfiConverterSequenceTypeMorpheme.lift(try rustCallWithError(FfiConverterTypeSudachiError_lift) {
    uniffi_sudachi_swift_fn_method_sudachitokenizer_tokenize_with_mode(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(text),
        FfiConverterTypeSplitMode_lower(mode),$0
    )
})
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSudachiTokenizer: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = SudachiTokenizer

    public static func lift(_ handle: UInt64) throws -> SudachiTokenizer {
        return SudachiTokenizer(unsafeFromHandle: handle)
    }

    public static func lower(_ value: SudachiTokenizer) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SudachiTokenizer {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: SudachiTokenizer, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSudachiTokenizer_lift(_ handle: UInt64) throws -> SudachiTokenizer {
    return try FfiConverterTypeSudachiTokenizer.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSudachiTokenizer_lower(_ value: SudachiTokenizer) -> UInt64 {
    return FfiConverterTypeSudachiTokenizer.lower(value)
}




/**
 * One analyzed unit of text with its full set of attributes.
 *
 * `begin`/`end` are **codepoint** (Unicode scalar) offsets into the
 * tokenized text — resolve them via `Morpheme.range(in:)` (or against
 * `text.unicodeScalars`), never as byte or `Character` offsets.
 */
public struct Morpheme: Equatable, Hashable {
    /**
     * The text of this morpheme exactly as it appears in the input.
     */
    public var surface: String
    /**
     * Katakana reading (e.g. テンキ for 天気). Convert with
     * `katakana_to_hiragana` for furigana.
     */
    public var readingForm: String
    /**
     * Dictionary (lemma) form, e.g. 行く for 行っ.
     */
    public var dictionaryForm: String
    /**
     * Normalized form unifying spelling variants, e.g. 付く for 附く.
     */
    public var normalizedForm: String
    /**
     * Part-of-speech hierarchy, most-general first (品詞, 6 levels).
     */
    public var partOfSpeech: [String]
    /**
     * Sudachi synonym group ids this morpheme belongs to (may be empty).
     */
    public var synonymGroupIds: [Int32]
    /**
     * True if the morpheme is out-of-vocabulary (not found in the dictionary).
     */
    public var isOov: Bool
    /**
     * Raw dictionary word id (stable within one dictionary build).
     */
    public var wordId: UInt32
    /**
     * Start offset in codepoints (Unicode scalars) within the input text.
     */
    public var begin: UInt32
    /**
     * End offset in codepoints (exclusive).
     */
    public var end: UInt32

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * The text of this morpheme exactly as it appears in the input.
         */surface: String, 
        /**
         * Katakana reading (e.g. テンキ for 天気). Convert with
         * `katakana_to_hiragana` for furigana.
         */readingForm: String, 
        /**
         * Dictionary (lemma) form, e.g. 行く for 行っ.
         */dictionaryForm: String, 
        /**
         * Normalized form unifying spelling variants, e.g. 付く for 附く.
         */normalizedForm: String, 
        /**
         * Part-of-speech hierarchy, most-general first (品詞, 6 levels).
         */partOfSpeech: [String], 
        /**
         * Sudachi synonym group ids this morpheme belongs to (may be empty).
         */synonymGroupIds: [Int32], 
        /**
         * True if the morpheme is out-of-vocabulary (not found in the dictionary).
         */isOov: Bool, 
        /**
         * Raw dictionary word id (stable within one dictionary build).
         */wordId: UInt32, 
        /**
         * Start offset in codepoints (Unicode scalars) within the input text.
         */begin: UInt32, 
        /**
         * End offset in codepoints (exclusive).
         */end: UInt32) {
        self.surface = surface
        self.readingForm = readingForm
        self.dictionaryForm = dictionaryForm
        self.normalizedForm = normalizedForm
        self.partOfSpeech = partOfSpeech
        self.synonymGroupIds = synonymGroupIds
        self.isOov = isOov
        self.wordId = wordId
        self.begin = begin
        self.end = end
    }

    

    
}

#if compiler(>=6)
extension Morpheme: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeMorpheme: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Morpheme {
        return
            try Morpheme(
                surface: FfiConverterString.read(from: &buf), 
                readingForm: FfiConverterString.read(from: &buf), 
                dictionaryForm: FfiConverterString.read(from: &buf), 
                normalizedForm: FfiConverterString.read(from: &buf), 
                partOfSpeech: FfiConverterSequenceString.read(from: &buf), 
                synonymGroupIds: FfiConverterSequenceInt32.read(from: &buf), 
                isOov: FfiConverterBool.read(from: &buf), 
                wordId: FfiConverterUInt32.read(from: &buf), 
                begin: FfiConverterUInt32.read(from: &buf), 
                end: FfiConverterUInt32.read(from: &buf)
        )
    }

    public static func write(_ value: Morpheme, into buf: inout [UInt8]) {
        FfiConverterString.write(value.surface, into: &buf)
        FfiConverterString.write(value.readingForm, into: &buf)
        FfiConverterString.write(value.dictionaryForm, into: &buf)
        FfiConverterString.write(value.normalizedForm, into: &buf)
        FfiConverterSequenceString.write(value.partOfSpeech, into: &buf)
        FfiConverterSequenceInt32.write(value.synonymGroupIds, into: &buf)
        FfiConverterBool.write(value.isOov, into: &buf)
        FfiConverterUInt32.write(value.wordId, into: &buf)
        FfiConverterUInt32.write(value.begin, into: &buf)
        FfiConverterUInt32.write(value.end, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMorpheme_lift(_ buf: RustBuffer) throws -> Morpheme {
    return try FfiConverterTypeMorpheme.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMorpheme_lower(_ value: Morpheme) -> RustBuffer {
    return FfiConverterTypeMorpheme.lower(value)
}


/**
 * Compact morpheme for the Swift display/merge pipeline. Carries only the
 * consumed fields, with `part_of_speech` pre-joined (matching how the
 * Swift side stores it) and a raw `pos_id` for cheap integer checks.
 */
public struct MorphemeLite: Equatable, Hashable {
    /**
     * The text of this morpheme exactly as it appears in the input.
     */
    public var surface: String
    /**
     * Dictionary (lemma) form.
     */
    public var dictionaryForm: String
    /**
     * Katakana reading.
     */
    public var readingForm: String
    /**
     * Part-of-speech hierarchy joined with commas, e.g. 名詞,普通名詞,一般,*,*,*.
     */
    public var partOfSpeech: String
    /**
     * Raw part-of-speech id for cheap integer comparisons.
     */
    public var posId: UInt16

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * The text of this morpheme exactly as it appears in the input.
         */surface: String, 
        /**
         * Dictionary (lemma) form.
         */dictionaryForm: String, 
        /**
         * Katakana reading.
         */readingForm: String, 
        /**
         * Part-of-speech hierarchy joined with commas, e.g. 名詞,普通名詞,一般,*,*,*.
         */partOfSpeech: String, 
        /**
         * Raw part-of-speech id for cheap integer comparisons.
         */posId: UInt16) {
        self.surface = surface
        self.dictionaryForm = dictionaryForm
        self.readingForm = readingForm
        self.partOfSpeech = partOfSpeech
        self.posId = posId
    }

    

    
}

#if compiler(>=6)
extension MorphemeLite: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeMorphemeLite: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> MorphemeLite {
        return
            try MorphemeLite(
                surface: FfiConverterString.read(from: &buf), 
                dictionaryForm: FfiConverterString.read(from: &buf), 
                readingForm: FfiConverterString.read(from: &buf), 
                partOfSpeech: FfiConverterString.read(from: &buf), 
                posId: FfiConverterUInt16.read(from: &buf)
        )
    }

    public static func write(_ value: MorphemeLite, into buf: inout [UInt8]) {
        FfiConverterString.write(value.surface, into: &buf)
        FfiConverterString.write(value.dictionaryForm, into: &buf)
        FfiConverterString.write(value.readingForm, into: &buf)
        FfiConverterString.write(value.partOfSpeech, into: &buf)
        FfiConverterUInt16.write(value.posId, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMorphemeLite_lift(_ buf: RustBuffer) throws -> MorphemeLite {
    return try FfiConverterTypeMorphemeLite.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMorphemeLite_lower(_ value: MorphemeLite) -> RustBuffer {
    return FfiConverterTypeMorphemeLite.lower(value)
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/**
 * Sudachi split granularity.
 *
 * Sudachi can segment the same text at three granularities. For
 * 国家公務員 ("national civil servant"): A → 国家 / 公務 / 員,
 * B → 国家 / 公務員, C → 国家公務員.
 */

public enum SplitMode: Equatable, Hashable {
    
    /**
     * Shortest units (UniDic-like) — best for search indexing.
     */
    case a
    /**
     * Middle units — a compromise between A and C.
     */
    case b
    /**
     * Named-entity-like longest units — best for display.
     */
    case c





}

#if compiler(>=6)
extension SplitMode: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSplitMode: FfiConverterRustBuffer {
    typealias SwiftType = SplitMode

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SplitMode {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .a
        
        case 2: return .b
        
        case 3: return .c
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: SplitMode, into buf: inout [UInt8]) {
        switch value {
        
        
        case .a:
            writeInt(&buf, Int32(1))
        
        
        case .b:
            writeInt(&buf, Int32(2))
        
        
        case .c:
            writeInt(&buf, Int32(3))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSplitMode_lift(_ buf: RustBuffer) throws -> SplitMode {
    return try FfiConverterTypeSplitMode.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSplitMode_lower(_ value: SplitMode) -> RustBuffer {
    return FfiConverterTypeSplitMode.lower(value)
}



/**
 * Errors thrown by dictionary loading and tokenization.
 *
 * Note: case names surface in Swift exactly as written here
 * (`.DictionaryNotFound`, …) — UniFFI does not lowercase error enum cases.
 */
public enum SudachiError: Swift.Error, Equatable, Hashable, Foundation.LocalizedError {

    
    
    /**
     * A system or user dictionary file does not exist at the given path.
     */
    case DictionaryNotFound(message: String)
    
    /**
     * A dictionary file exists but cannot be loaded (bad header/format).
     */
    case DictionaryInvalid(message: String)
    
    /**
     * The configuration or resource directory is invalid.
     */
    case ConfigInvalid(message: String)
    
    /**
     * Tokenization itself failed (e.g. input longer than ~49 KB).
     */
    case Tokenization(message: String)
    

    

    

    
    public var errorDescription: String? {
        String(reflecting: self)
    }
    
}

#if compiler(>=6)
extension SudachiError: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSudachiError: FfiConverterRustBuffer {
    typealias SwiftType = SudachiError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SudachiError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .DictionaryNotFound(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 2: return .DictionaryInvalid(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 3: return .ConfigInvalid(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 4: return .Tokenization(
            message: try FfiConverterString.read(from: &buf)
        )
        

        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: SudachiError, into buf: inout [UInt8]) {
        switch value {

        

        
        case .DictionaryNotFound(_ /* message is ignored*/):
            writeInt(&buf, Int32(1))
        case .DictionaryInvalid(_ /* message is ignored*/):
            writeInt(&buf, Int32(2))
        case .ConfigInvalid(_ /* message is ignored*/):
            writeInt(&buf, Int32(3))
        case .Tokenization(_ /* message is ignored*/):
            writeInt(&buf, Int32(4))

        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSudachiError_lift(_ buf: RustBuffer) throws -> SudachiError {
    return try FfiConverterTypeSudachiError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSudachiError_lower(_ value: SudachiError) -> RustBuffer {
    return FfiConverterTypeSudachiError.lower(value)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceInt32: FfiConverterRustBuffer {
    typealias SwiftType = [Int32]

    public static func write(_ value: [Int32], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterInt32.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [Int32] {
        let len: Int32 = try readInt(&buf)
        var seq = [Int32]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterInt32.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]

    public static func write(_ value: [String], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterString.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String] {
        let len: Int32 = try readInt(&buf)
        var seq = [String]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterString.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeMorpheme: FfiConverterRustBuffer {
    typealias SwiftType = [Morpheme]

    public static func write(_ value: [Morpheme], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeMorpheme.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [Morpheme] {
        let len: Int32 = try readInt(&buf)
        var seq = [Morpheme]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeMorpheme.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeMorphemeLite: FfiConverterRustBuffer {
    typealias SwiftType = [MorphemeLite]

    public static func write(_ value: [MorphemeLite], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeMorphemeLite.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [MorphemeLite] {
        let len: Int32 = try readInt(&buf)
        var seq = [MorphemeLite]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeMorphemeLite.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceSequenceTypeMorphemeLite: FfiConverterRustBuffer {
    typealias SwiftType = [[MorphemeLite]]

    public static func write(_ value: [[MorphemeLite]], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterSequenceTypeMorphemeLite.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [[MorphemeLite]] {
        let len: Int32 = try readInt(&buf)
        var seq = [[MorphemeLite]]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterSequenceTypeMorphemeLite.read(from: &buf))
        }
        return seq
    }
}
/**
 * Convert a Sudachi-style katakana reading to hiragana, e.g. for furigana
 * display. Only the katakana block U+30A1..U+30F6 is mapped; everything
 * else (ASCII, kanji, the prolonged sound mark ー) passes through.
 */
public func katakanaToHiragana(s: String) -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_sudachi_swift_fn_func_katakana_to_hiragana(
        FfiConverterString.lower(s),$0
    )
})
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 30
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_sudachi_swift_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_sudachi_swift_checksum_func_katakana_to_hiragana() != 51498) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_sudachi_swift_checksum_method_sudachitokenizer_tokenize() != 50583) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_sudachi_swift_checksum_method_sudachitokenizer_tokenize_lite() != 25636) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_sudachi_swift_checksum_method_sudachitokenizer_tokenize_lite_with_mode() != 25613) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_sudachi_swift_checksum_method_sudachitokenizer_tokenize_many() != 65364) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_sudachi_swift_checksum_method_sudachitokenizer_tokenize_many_with_mode() != 51213) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_sudachi_swift_checksum_method_sudachitokenizer_tokenize_with_mode() != 12849) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_sudachi_swift_checksum_constructor_sudachidictionary_new() != 33628) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_sudachi_swift_checksum_constructor_sudachitokenizer_new() != 33275) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureSudachiSwiftInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all