#!/usr/bin/env bash
# Lint the hand-written Swift with swift-format (the official Swift.org tool,
# bundled with the Swift 6 toolchain). The generated bindings
# (Sources/Sudachi/Sudachi.swift) are excluded — they're machine-generated by
# build-ios.sh and not ours to style.
#
# Pass --fix to reformat in place instead of just checking.

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

MODE="${1:-check}"

# All hand-written Swift = everything under swift/Sudachi except the generated
# bindings file (matched by full path so a future test file named Sudachi.swift
# would not be silently skipped). Paths have no spaces, so a word-split
# expansion is fine (and portable to the macOS system bash 3.2, which lacks
# `mapfile`).
# shellcheck disable=SC2046
set -- $(find swift/Sudachi/Sources swift/Sudachi/Tests -name '*.swift' \
  ! -path 'swift/Sudachi/Sources/Sudachi/Sudachi.swift')

if [ "$MODE" = "--fix" ]; then
  swift format --in-place --configuration .swift-format "$@"
  echo "swift-format: reformatted $# file(s)"
else
  swift format lint --strict --configuration .swift-format "$@"
  echo "swift-format: clean ($# file(s))"
fi
